apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: mastodon-de
  namespace:  pulumi-apps
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.2-0
  postgresVersion: 16
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.49-0
      configuration:
      - secret:
          name: pg-cluster-s3-secret
      global:
        repo1-s3-uri-style: path
      repos:
      - name: repo1
        s3:
          bucket: "pg-backup"
          endpoint: "us-west-1.storage.impossibleapi.net.storage.impossibleapi.net"
          region: "us-west-1"