
  # redis:
  #   restart: always
  #   image: redis:7-alpine
  #   networks:
  #     - internal_network
  #   healthcheck:
  #     test: ['CMD', 'redis-cli', 'ping']
  #   volumes:
  #     - ./redis:/data


apiVersion:           apps/v1
kind:                 Deployment
metadata:
  name:               redis
  labels:
    app:              redis
spec:
  replicas:           1
  selector:
    matchLabels:
      app:            redis
  template:
    metadata:
      labels:
        app:          redis
    spec:
      containers:
      - name:         redis
        image:        redis:7-alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory:   200Mi
            cpu:      1
          requests:
            memory:   100Mi
            cpu:      100m
        volumeMounts:
        - mountPath:  /data
          name:       cache-volume
      volumes:
      - name:         cache-volume
        emptyDir:
          sizeLimit:  100Mi

