---

  # streaming:
  #   build: .
  #   image: ghcr.io/mastodon/mastodon:v4.2.7
  #   restart: always
  #   env_file: .env.production
  #   command: node ./streaming
  #   networks:
  #     - external_network
  #     - internal_network
  #   healthcheck:
  #     # prettier-ignore
  #     test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
  #   ports:
  #     - '127.0.0.1:4000:4000'
  #   depends_on:
  #     - db
  #     - redis
