---

- name: patch secret for mTLS
  ansible.builtin.shell: |
                kubectl create secret generic \
                  mtls-ca \
                  --from-file=tls.ca={{ k3s_mtls_dir }}/mtls-root-ca.crt \
                  --save-config \
                  --dry-run=client \
                  -o yaml | \
                tee /tmp/{{ item }}-mtls-root-ca.yaml
  register:     secretYAML

- debug:
    msg:        "secretYAML ( {{ ansible_check_mode }}): {{ secretYAML.stdout | to_yaml }}"
  when:         debug_mode is defined

- name: Add secret
  kubernetes.core.k8s:
    state:      "{{ k3s_mtls_state }}"
    kubeconfig: "{{ global_kubeconfig }}"
    namespace:  "{{ item }}"
    src:        /tmp/{{ item }}-mtls-root-ca.yaml
  when:         not ansible_check_mode


