---

- name:           Remove old client certificate
  ansible.builtin.file:
    path:         "{{ k3s_mtls_dir }}/mtls-client-ca.crt"
    state:        absent
  when:           k3s_refresh_client_certificate == true


- name:           Remove old browser client certificate
  ansible.builtin.file:
    path:         "{{ k3s_mtls_dir }}/mtls-client-ca.p12"
    state:        absent
  when:           k3s_refresh_client_certificate == true

- name:           create mtls-client-ca
  ansible.builtin.shell: |
                  step  certificate create                              \
                  "{{ inventory_hostname_short }} mTLS client certificate" \
                  {{ k3s_mtls_dir }}/mtls-client-ca.crt                 \
                  {{ k3s_mtls_dir }}/mtls-client-ca.key                 \
                  --no-password                                         \
                  --insecure                                            \
                  --profile leaf                                        \
                  --san mtls-client-ca.olaf-radicke.de                  \
                  --not-after 2160h                                     \
                  --kty RSA                                             \
                  --size 4096                                           \
                  --ca {{ k3s_mtls_dir }}/mtls-intermediate-ca.crt      \
                  --ca-key {{ k3s_mtls_dir }}/mtls-intermediate-ca.key  \
                  --bundle \
                  --force
  args:
    creates:      "{{ k3s_mtls_dir }}/mtls-client-ca.crt"

- name:           check mtls-client-ca.crt
  ansible.builtin.shell: |
                  step certificate inspect --short {{ k3s_mtls_dir }}/mtls-client-ca.crt
  register:       shell_result

- debug:
    msg:          "{{ shell_result }}"
  when:
    -             shell_result is defined
    -             debug_mode is defined

- name:           double check mtls-client-ca.crt
  ansible.builtin.shell: |
                  step certificate verify                       \
                    {{ k3s_mtls_dir }}/mtls-client-ca.crt       \
                    --roots {{ k3s_mtls_dir }}/mtls-root-ca.crt
  register:       shell_result

- debug:
    msg:          "{{ shell_result }}"
  when:
    -             shell_result is defined
    -             debug_mode is defined

- name:           covert client certificate to PKCS#12
  ansible.builtin.shell: |
                  step certificate p12                             \
                  {{ k3s_mtls_dir }}/mtls-client-ca.p12            \
                  {{ k3s_mtls_dir }}/mtls-client-ca.crt            \
                  {{ k3s_mtls_dir }}/mtls-client-ca.key            \
                  --ca {{ k3s_mtls_dir }}/mtls-intermediate-ca.crt \
                  --no-password                                    \
                  --insecure                                       \
                  --force
  args:
    creates:      "{{ k3s_mtls_dir }}/mtls-client-ca.p12"

# - name:           Delete the directory for client certificate download
#   ansible.builtin.file:
#     path:         "{{ k3s_download_dir }}"
#     state:        absent
#   delegate_to:    localhost
#   when:           k3s_refresh_client_certificate == true

- name:           download client certificate
  ansible.builtin.fetch:
    src:          "{{ k3s_mtls_dir }}/{{ item }}"
    dest:         "{{ k3s_download_dir }}"
  loop:
    - "mtls-client-ca.p12"
    - "mtls-client-ca.crt"
    - "mtls-client-ca.key"