---

- name:           Remove old intermediate certificate
  ansible.builtin.file:
    path:         "{{ k3s_mtls_dir }}/mtls-intermediate-ca.crt"
    state:        absent
  when:           k3s_refresh_inter_certificate == true

- name:           create mtls-intermediate-ca
  ansible.builtin.shell: |
                  step  certificate create                      \
                  "mTLS Intermediate CA"                        \
                  {{ k3s_mtls_dir }}/mtls-intermediate-ca.crt   \
                  {{ k3s_mtls_dir }}/mtls-intermediate-ca.key   \
                  --no-password                                 \
                  --insecure                                    \
                  --profile intermediate-ca                     \
                  --san mtls-intermediate-ca.olaf-radicke.de    \
                  --not-after 8760h                             \
                  --kty RSA                                     \
                  --size 4096                                   \
                  --ca {{ k3s_mtls_dir }}/mtls-root-ca.crt      \
                  --ca-key {{ k3s_mtls_dir }}/mtls-root-ca.key  \
                  --force
  args:
    creates:      "{{ k3s_mtls_dir }}/mtls-intermediate-ca.crt"



- name:           check mtls-intermediate-ca.crt
  ansible.builtin.shell: |
                  step certificate inspect --short {{ k3s_mtls_dir }}/mtls-intermediate-ca.crt
  register:       shell_result

- debug:
    msg:          "{{ shell_result }}"
  when:
    -             shell_result is defined
    -             debug_mode is defined

