---

# ansible_host:                     2a01:4f9:c010:8e06::1
ansible_host:                     65.108.52.28
ansible_user:                     "root"
ansible_become:                   yes
ansible_python_interpreter:       "/usr/bin/python3"

# ---- GLOBAL ----

global_kubeconfig:                "/etc/rancher/k3s/k3s.yaml"

k3s_namespace:                    "live"
# k3s_deployment_state:           "absent"
k3s_namespaces:
  -                               "default"
  -                               "live"
  -                               "fluxcd"


# ---- K3s ----

k3s_install_with_pull_secret:     false

# ---- letsencrypt ----

k3s_cert_manager_mail:            "breiefkasten@olaf-radicke.de"

# ----- MariaDB operator ----

mariadb_operator_state:  "absent"

# ----- Postgres operator -----

postgres_operator_state: "present"

# ------ PVCs ----------------

persistent_volumes_state: "present"
persistent_volumes_pvcs:
  -                       mastodon-01
  -                       mastodon-02
  -                       friendica-01