---

apiVersion:     argoproj.io/v1alpha1
kind:           AppProject
metadata:
  name:         mastodon-db
  namespace:    argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    -           resources-finalizer.argocd.argoproj.io
spec:
  description:  Postgres cluster for Mastodon
  sourceRepos:
  -             '*'
  destinations:
  - namespace:  'argocd-aoa'
    server:     '*'