---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mastodon
  namespace:  fluxcd
spec:
  interval: 60m
  url: https://charts.bitnami.com/bitnami

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mastodon
  namespace:  fluxcd
spec:
  chart:
    spec:
      chart: mastodon
      version: "4.7.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 1m
  values:
    replicas: 1