---

apiVersion:                 v1
kind:                       PersistentVolume
metadata:
  name:                     local-pv
  labels:
    type:                   local
spec:
  storageClassName:         local-storage
  capacity:
    storage:                500Mi
  volumeMode:               Filesystem
  accessModes:
    -                       ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path:                   /srv/k8s-pvc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key:              kubernetes.io/hostname
          operator:         In
          values:
          -                 ubuntu-4gb-hel1-3

