---

apiVersion:         argoproj.io/v1alpha1
kind:               Application
metadata:
  name:             ingress-raw
  namespace:        argocd
spec:
  project:          ingress-raw
  source:
    repoURL:        https://github.com/quakers-social/crash-and-burn.git
    targetRevision: HEAD
    path:           argocd/raw-projects/ingress
  destination:
    server:         https://kubernetes.default.svc
    namespace:      argocd-aoa