---

apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: misskey-db
  namespace:  argocd-aoa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  openshift: false
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.2-0
  postgresVersion: 16
  instances:
    - name: misskey-db-01
      replicas: 1
      resources:
        limits:
          cpu: 1.0
          memory: 1.4Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
  users:
    - name: misskey
      databases:
        - misskey
      options: "SUPERUSER"
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host all all 0.0.0.0/0 md5" # this line enabled logical replication with programmatic access
          - "host all postgres 127.0.0.1/32 md5"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.49-0
      configuration:
        - secret:
            name: postgres-s3-backup-secret
      global:
        repo1-s3-uri-style: path
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
        - name: repo1
          schedules:
            full: "0 1 * * 0"
            differential: "0 1 * * 1-6"
          s3:
            bucket: "pg-backup"
            endpoint: "us-west-1.storage.impossibleapi.net"
            region: "us-west-1"
      manual:
        repoName: repo1
        options:
         - --type=full
