---

apiVersion: v1
kind: Secret
metadata:
  name: mastodon-env-production
stringData:
  .env.production: |
    DB_HOST=db
    DB_PORT=5432
    DB_NAME=postgres
    DB_USER=postgres
    DB_PASS=XXXXX
    REDIS_HOST=redis
    REDIS_PORT=6379
    REDIS_PASSWORD=XXXX