---


apiVersion:           apps/v1
kind:                 Deployment
metadata:
  name:               mastodon-web
  labels:
    app:              mastodon-web
spec:
  replicas:           1
  selector:
    matchLabels:
      app:            mastodon-web
  template:
    metadata:
      labels:
        app:          mastodon-web
    spec:
      containers:
      - name:         mastodon-sidekiq
        image:        ghcr.io/mastodon/mastodon:v4.2.7
        command:      ["bundle"]
        args:         ["exec", "sidekiq"]
        livenessProbe:
          exec:
            command:
            - "CMD-SHELL"
            - "ps"
            - "aux"
            - "|"
            - "grep"
            - '[s]idekiq\ 6'
            - "||"
            - "false"
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory:   200Mi
            cpu:      1
          requests:
            memory:   100Mi
            cpu:      100m
        volumeMounts:
        - name:       mastodon-system
          mountPath:  /mastodon/public
          # mountPath:  /mastodon/public/system
        - name:       secret-volume
          readOnly: true
          mountPath:  "/opt/mastodon"
      volumes:
      - name:         mastodon-system
        persistentVolumeClaim:
          claimName:  mastodon-system
      - name:         mastodon-assets
        persistentVolumeClaim:
          claimName:  mastodon-assets
      - name:         secret-volume
        secret:
          secretName: mastodon-env-production


