---

  # sidekiq:
  #   build: .
  #   image: ghcr.io/mastodon/mastodon:v4.2.7
  #   restart: always
  #   env_file: .env.production
  #   command: bundle exec sidekiq
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - external_network
  #     - internal_network
  #   volumes:
  #     - ./public/system:/mastodon/public/system
  #   healthcheck:
  #     test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

