---

apiVersion:           apps/v1
kind:                 Deployment
metadata:
  name:               mastodon-web
  labels:
    app:              mastodon-web
spec:
  replicas:           1
  selector:
    matchLabels:
      app:            mastodon-web
  template:
    metadata:
      labels:
        app:          mastodon-web
    spec:
      # initContainers:
      # - name:         mastodon-web-init
      #   image:        olafradicke/mastodon-web:0.5.1
      #   resources:
      #     limits:
      #       memory:   200Mi
      #       cpu:      1
      #     requests:
      #       memory:   100Mi
      #       cpu:      100m
      #   env:
      #   - name: RAILS_ENV
      #     value: "production"
      # #   command: ["rake", "db:migrate"]
      #   command: ["rails", "assets:precompile"]
      #   volumeMounts:
      #   - name:       mastodon-system
      #     mountPath:  /home/mastodon/.rbenv/live/public/system
      #   - name:       mastodon-assets
      #     mountPath:  /home/mastodon/.rbenv/live/public/assets
      #   - name:       secret-volume
      #     readOnly: true
      #     mountPath:  "/home/mastodon/.rbenv/live/.env.production"
      #     subPath:    ".env.production"
      containers:
      - name:         mastodon-web
        image:        olafradicke/mastodon-web:4.2.8.0
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory:   200Mi
            cpu:      1
          requests:
            memory:   100Mi
            cpu:      100m
        env:
        - name: RAILS_ENV
          value: "production"
        - name: RAILS_LOG_LEVEL
          value: "debug"
        - name: DB_HOST
          value: "mastodon-db-primary.argocd-aoa.svc"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: mastodon-db
        - name: DB_USER
          value: astodonsu
        - name: DB_PASS
          value: ',kLU.j}pCSja80)eogOL9iMh'
        volumeMounts:
        - name:       mastodon-system
          mountPath:  /home/mastodon/.rbenv/live/public/system
        - name:       mastodon-assets
          mountPath:  /home/mastodon/.rbenv/live/public/assets
        - name:       secret-volume
          readOnly: true
          mountPath:  "/home/mastodon/.rbenv/live/.env.production"
          subPath:    ".env.production"
      volumes:
      - name:         mastodon-system
        persistentVolumeClaim:
          claimName:  mastodon-system
      - name:         mastodon-assets
        persistentVolumeClaim:
          claimName:  mastodon-assets
      - name:         secret-volume
        secret:
          secretName: mastodon-env-production


