---


- name:                   Create local directories
  ansible.builtin.file:
    path:                 "/srv/persistent-volume-{{ item }}"
    state:                directory
  loop:                   "{{ persistent_volumes_pvcs }}"

- name:                   Create PVs
  kubernetes.core.k8s:
    kubeconfig:           "{{ k3s_kubeconfig }}"
    state:                "{{ persistent_volumes_state }}"
    wait:                 "yes"
    definition:
      kind:               PersistentVolume
      apiVersion:         v1
      metadata:
        name:             "local-{{ item }}"
        labels:
          type:           local
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
      spec:
        storageClassName: "local-{{ item }}"
        capacity:
          storage:        20Gi
        accessModes:
          -               ReadWriteMany
          # -                   ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        local:
          path:           "/srv/persistent-volume-{{ item }}"
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key:      kubernetes.io/hostname
                operator: In
                values:
                -         ubuntu-4gb-hel1-3
  loop:                   "{{ persistent_volumes_pvcs }}"

- name:                   Create StorageClass
  kubernetes.core.k8s:
    kubeconfig:           "{{ k3s_kubeconfig }}"
    state:                absent
    wait:                 "yes"
    definition:
      apiVersion:         storage.k8s.io/v1
      kind:               StorageClass
      metadata:
        name:             "local-{{ item }}"
  loop:                   "{{ persistent_volumes_pvcs }}"

- name:                   Create StorageClass
  kubernetes.core.k8s:
    kubeconfig:           "{{ k3s_kubeconfig }}"
    state:                "{{ persistent_volumes_state }}"
    wait:                 "yes"
    definition:
      apiVersion:         storage.k8s.io/v1
      kind:               StorageClass
      metadata:
        name:             "local-{{ item }}"
      provisioner:        kubernetes.io/no-provisioner
      volumeBindingMode:  Immediate
  loop:                   "{{ persistent_volumes_pvcs }}"