---

# A pod for debogging

apiVersion:                 apps/v1
kind:                       Deployment
metadata:
  name:                     debugging-host
  namespace:                pulumi-apps
spec:
  replicas:                 1
  selector:
    matchLabels:
      app:                  debugging-host
  template:
    metadata:
      labels:
        app:                debugging-host
    spec:
      containers:
        - name:             debugging-host
          image:            fedora:39
          imagePullPolicy:  "IfNotPresent"
          resources:
            requests:
              memory:       "64Mi"
              cpu:          "250m"
            limits:
              memory:       "128Mi"
              cpu:          "500m"
          ports:
            - containerPort: 5432
          env:
          - name:           LANG
            value:          de_DE
          command:          ["/bin/sh"]
          args:             ["-c", "while true; do echo hello; sleep 10;done"]
