---


- name: create ArgoCD namespace
  kubernetes.core.k8s:
    kubeconfig:         "{{ global_kubeconfig }}"
    name:               "{{ argocd_namespace }}-aoa"
    api_version:        v1
    kind:               Namespace
    state:              present
    wait:               yes


- name: add projekt for app-of-app
  kubernetes.core.k8s:
    kubeconfig:         "{{ global_kubeconfig }}"
    state:              "{{ argocd_aoa_state }}"
    namespace:          "argocd"
    definition:
      apiVersion:       argoproj.io/v1alpha1
      kind:             AppProject
      metadata:
        name:           app-of-app
        namespace:      "argocd"
        finalizers:
                        - resources-finalizer.argocd.argoproj.io
      spec:
        description:    project of apps of apps from plain yaml
        sourceRepos:
                        - '*'
        destinations:
        # - namespace:            argocd-raw-apps
        #   server:               https://kubernetes.default.svc
        #   name:                 in-cluster
        # - namespace:            argocd-raw-apps-03
        #   server:               https://kubernetes.default.svc
        #   name:                 in-cluster
        clusterResourceWhitelist:
        - group:        ''
          kind:         Namespace

- name: application for app-of-app
  kubernetes.core.k8s:
    kubeconfig:         "{{ global_kubeconfig }}"
    state:              "{{ argocd_aoa_state }}"
    namespace:          "argocd"
    definition:
      apiVersion:       argoproj.io/v1alpha1
      kind:             Application
      metadata:
        name:           app-of-app-test-app
        namespace:      "argocd"
        finalizers:
                        - resources-finalizer.argocd.argoproj.io
      spec:
        project:        default
        syncPolicy:
          automated:
            prune:      true
          syncOptions:
                        - PruneLast=true
                        - Replace=true
                        - CreateNamespace=true
        source:
          repoURL:      https://github.com/quakers-social/crash-and-burn.git
          targetRevision: "{{ argocd_aoa_gitbranch }}"
          path:         "{{ argocd_aoa_gitpath }}"
          directory:
            recurse:    true
        destination:
          server:       https://kubernetes.default.svc
          namespace:    argocd

