---

- name: delete ArgoCD namespace
  kubernetes.core.k8s:
    kubeconfig:         "{{ global_kubeconfig }}"
    name:               "{{ argocd_namespace }}"
    api_version:        v1
    kind:               Namespace
    state:              absent
    wait:               yes
  when:                 argocd_reset == true

- name: create ArgoCD namespace
  kubernetes.core.k8s:
    kubeconfig:         "{{ global_kubeconfig }}"
    name:               "{{ argocd_namespace }}"
    api_version:        v1
    kind:               Namespace
    state:              present
    wait:               yes


- name: Download argocd operator
  ansible.builtin.get_url:
    url:                "{{ argocd_download_url }}"
    dest:               "/tmp/argo-insecure-install.yaml"
    mode:               '0440'

- name: Install ArgoCD with yaml file
  kubernetes.core.k8s:
    kubeconfig:         "{{ global_kubeconfig }}"
    state:              present
    namespace:          "argocd"
    # wait:               yes
    wait_timeout:       240
    src:                "/tmp/argo-insecure-install.yaml"

- name:           Setup app of app
  include_tasks:  app-of-app.yaml

