---

#   app:
#     build: ./app
#     restart: always
#     volumes:
#       - friendica:/var/www/html
#     environment:
#       - FRIENDICA_ADMIN_MAIL=
#       - FRIENDICA_TZ=
#       - FRIENDICA_LANG=
#       - FRIENDICA_URL=
#       - FRIENDICA_SITENAME=
#       - SMTP=
#     env_file:
#       - db.env
#     depends_on:
#       - db

apiVersion:               apps/v1
kind:                     Deployment
metadata:
  name:                   friendica-app
  labels:
    app:                  friendica-app
spec:
  replicas:               1
  selector:
    matchLabels:
      app:                friendica-app
  # securityContext:
  #   runAsUser:            1000
  #   runAsGroup:           1000
  #   fsGroup:              1000
  #   fsGroupChangePolicy:  "Always"
  template:
    metadata:
      labels:
        app:              friendica-app
    spec:
      containers:
      - name:             friendica-app
        image:            friendica:2024.03-fpm-alpine
        # securityContext:
        #   runAsUser:      1000
        #   allowPrivilegeEscalation: false
        # livenessProbe:
        #   httpGet:
        #     path:         /health
        #     port:         3000
        #   initialDelaySeconds: 15
        #   periodSeconds:  10
        # readinessProbe:
        #   tcpSocket:
        #     port:         9000
        #   initialDelaySeconds: 15
        #   periodSeconds:  10
        ports:
        - containerPort:  9000
        resources:
          limits:
            memory:       200Mi
            cpu:          1
          requests:
            memory:       100Mi
            cpu:          100m
        env:
        - name:           FRIENDICA_URL
          value:          "friendica.the-independent-friend.de"
        - name:           FRIENDICA_TZ
          value:          "Europe/Berlin"
        - name:           FRIENDICA_SITENAME
          value:          "friendica.the-independent-friend"
        - name:           FRIENDICA_NO_VALIDATION
          value:          "true"
        - name:           FRIENDICA_DATA_DIR
          value:          "/var/www/data"
        - name:           FRIENDICA_UPGRADE
          value:          "fals"
        - name:           FRIENDICA_DEBUGGING
          value:          "true"
        - name:           FRIENDICA_LOGLEVEL
          value:          "notice"
        - name:           FRIENDICA_LOGGER
          value:          "stream"
        - name:           MYSQL_USER
          value:          "stream"
        - name:           MYSQL_PASSWORD
          value:          "stream"
        - name:           MYSQL_DATABASE
          value:          "stream"
        - name:           MYSQL_HOST
          value:          "stream"
        - name:           MYSQL_PORT
          value:          "3306"
        - name:           REDIS_HOST
          value:          "redis"
        - name:           PHP_UPLOAD_LIMIT
          value:          "512M"
        - name:           SMTP
          value:          "smtp.mail.nix"
        - name:           SMTP_DOMAIN
          value:          "friendica.the-independent-friend.de"
        - name:           SMTP_AUTH_USER
          value:          "friendica"
        - name:           SMTP_AUTH_PASS
          value:          "XXXXXXXX"
        volumeMounts:
        - name:       friendica-system
          mountPath:  /var/www/html
      volumes:
      - name:         friendica-system
        persistentVolumeClaim:
          claimName:  friendica-system


