

---

apiVersion:         v1
kind:               PersistentVolumeClaim
metadata:
  name:             friendica-system
spec:
  storageClassName: local-friendica-01
  accessModes:
    -               ReadWriteMany
  resources:
    requests:
      storage:      10Gi

