---

- name: create namespaces
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ flux_cd_state }}"
    wait:                       "yes"
    definition:
      api_version:              v1
      kind:                     Namespace
      metadata:
        name:                   "{{ flux_cd_namespaces }}"
        labels:
          name:                 "{{ flux_cd_namespaces }}"


- name: download operator
  ansible.builtin.get_url:
    url:                        "{{ flux_cd_download }}"
    dest:                       "/tmp/flux_cd.yaml"
    mode:                       '0440'

- name: create operator
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ flux_cd_state }}"
    wait:                       "yes"
    src:                        "/tmp/flux_cd.yaml"
  when:                         not ansible_check_mode


- name: create GitRepository
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ flux_cd_state }}"
    wait:                       "yes"
    definition:
      apiVersion:               source.toolkit.fluxcd.io/v1
      kind:                     GitRepository
      metadata:
        name:                   crash-and-burn
        namespace:              "flux-system"
      spec:
        interval:               60m
        prune:                  true
        url:                    https://github.com/quakers-social/crash-and-burn.git
        ref:
          branch:               main

- name: create Kustomization
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ flux_cd_state }}"
    wait:                       "yes"
    definition:
      apiVersion:               kustomize.toolkit.fluxcd.io/v1
      kind:                     Kustomization
      metadata:
        name:                   mastodon
        namespace:              "flux-system"
      spec:
        interval:               1m
        prune:                  true
        sourceRef:
          kind:                 GitRepository
          name:                 crash-and-burn
        path:                   ./fluxcd/apps/mastodon