---

apiVersion: helm.k8s.mariadb.com/v1alpha1
kind: MariadbOperator
metadata:
  name: mariadb-operator
spec:
  image:
    repository: ghcr.io/mariadb-operator/mariadb-operator
    pullPolicy: IfNotPresent
  logLevel: INFO
  ha:
    enabled: true
  # metrics:
  #   enabled: true
  #   serviceMonitor:
  #     enabled: true
  # webhook:
  #   cert:
  #     certManager:
  #       enabled: true