apiVersion: k8s.mariadb.com/v1alpha1
kind:               MariaDB
metadata:
  name:             friendica-db
spec:
  rootPasswordSecretKeyRef:
    name:           mariadb-passwords
    key:            root-password

  username:         friendica
  passwordSecretKeyRef:
    name:           mariadb-passwords
    key:            user-password
  database:         friendica

  image:            mariadb:10.11.7
  imagePullPolicy:  IfNotPresent

  port:             3306

  storage:
    size:           1Gi

  service:
    type:           ClusterIP

  myCnf: |
                    [mariadb]
                    bind-address=*
                    default_storage_engine=InnoDB
                    binlog_format=row
                    innodb_autoinc_lock_mode=2
                    max_allowed_packet=256M

  metrics:
    enabled: true
