---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariabackup
spec:
  storageClassName: local-local-friendica-01
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
