---

name: Pulumi dry run
on:
  push:
    tags-ignore:
      - '*'
jobs:
  pulumiDryRun:
    name: Pulimi dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: dev
          work-dir: ./pulumi
          cloud-url: file://./
          secrets-provider: passphrase
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}