---

name: Pulumi
on: push
  # push:
  #   tags:
  #     - '*'
jobs:
  pulumiDryRun:
    name: Pulumi dry run
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: downloading go mod dependencies
        run: cd ./pulumi && go mod download
      - name: Pulumi up
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: dev
          work-dir: ./pulumi
          cloud-url: file://./
          secrets-provider: passphrase
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
  pulumiUp:
    name: Pulumi run
    if: github.ref_type == 'tag'
    needs:
      - pulumiDryRun
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: install kubernetes dependencis
        run: ./scripts/install_k8s_dependencies.sh
      - name: create kubeconfig
        run: echo "${KUBE_CONFIG}" >  ${KUBECONFIG} && wc $(pwd)/${KUBECONFIG}
        env:
          KUBECONFIG: "/home/runner/work/crash-and-burn/crash-and-burn/kubeconfig"
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      # - name: create kubeconfig
      #   uses: mobiledevops/secret-to-file-action@v1
      #   with:
      #     base64-encoded-secret: ${{ secrets.KUBE_CONFIG }}
      #     filename: "~/.kube/config"
      - name: Pulumi up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: dev
          work-dir: ./pulumi
          cloud-url: file://./
          secrets-provider: passphrase
        env:
          KUBECONFIG: "/home/runner/work/crash-and-burn/crash-and-burn/kubeconfig"
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}