---

name: Run Ansible
run-name: ${{ github.actor }} run setuo VM.
on: push
# on:
#   push:
#     tags:
#       - '*'
jobs:
  dryRun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Get GitHub Tag Name
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v4
        with:
          playbook: install_and_update.yaml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          known_hosts: |
            mastodon.the-independent-friend.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJAcpDId6LxMxyI8RnRq7GZctKMS5eOZa+hX/1G5fYGf
          options: |
            --inventory .hosts
            --verbose
            --check
  setupRemote:
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    needs:
      - dryRun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v4
        with:
          # Required, playbook filepath
          playbook: install_and_update.yaml
          # Optional, directory where playbooks live
          directory: ./ansible
          # Optional, ansible configuration file content (ansible.cfg)
          # configuration: |
          #   [defaults]
          #   callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
          #   stdout_callback = yaml
          #   nocows = false
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          # inventory: |
          #   [all]
          #   example.com

          #   [group1]
          #   example.com
          # Optional, SSH known hosts file content
          known_hosts: |
            mastodon.the-independent-friend.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJAcpDId6LxMxyI8RnRq7GZctKMS5eOZa+hX/1G5fYGf
          # Optional, encrypted vault password
          vault_password: ${{secrets.VAULT_PASSWORD}}
          # Optional, galaxy requirements filepath
          # requirements: galaxy-requirements.yml
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --inventory .hosts
            --extra-vars hello=there
            --verbose
            --diff