apiVersion:         argoproj.io/v1alpha1
kind:               Application
metadata:
  name:             mariadb-operator
  namespace:        argocd
spec:
  project:          mariadb-operator
  source:
    chart:          mariadb-operator
    repoURL:        https://mariadb-operator.github.io/mariadb-operator
    targetRevision: 0.27.0
    helm:
      releaseName:  sealed-secrets
  destination:
    server:         https://kubernetes.default.svc
    namespace:      argocd-aoa